type=item
items=leather_helmet
texture.leather_helmet=lunettes_icon1
texture.leather_helmet_overlay=lunettes_icon_overlay1
nbt.display.Name=iregex:.*Lunettes.*(scientifique|Theoriciennes).*
nbt.theo=lunettes