type=armor
matchItems=leather_leggings
texture.leather_layer_2=scaphandre_base
texture.leather_layer_2_overlay=scaphandre2overlay
components.custom_data.armure=scaphandre

# /give @s leather_leggings[custom_data={armure:scaphandre}]
